spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/mypetdiary
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  thymeleaf:
    cache: false

server:
  port: 8081

jwt:
  secret: a21ob29uLW15LXBldC1kaWFyeS1hcHBsaWNhdGlvbi1kaWFyeS1wZXQtbXkta21ob29u
  time:
    access: 3600000
    refresh: 86400000

diary:
  security:
    ignore-pattern: /api/auth/user/**
